// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import { join } from "path";
import { existsSync } from "fs";
import { config } from "dotenv";

// Load .env.local if it exists (for Next.js parity)
const localEnv = join(process.cwd(), ".env.local");
if (existsSync(localEnv)) {
  config({ path: localEnv, override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.cjs",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
